"""Build the dispatch table.

The rule is deliberately conservative, because the thing it protects is the
claim that the shipped model is never slower and never wrong:

1. Group cases by `dispatch_key` -- the geometry a running model can identify
   from its own inputs. Padded and dense variants of one geometry land in the
   same group, because the model cannot tell them apart without a device sync.
2. A candidate is eligible for a group only if it passed the zero-bad-element
   check on **every** case in that group.
3. Its score is its **worst** speedup across the group, not its average. A
   candidate that wins big on one case and loses on another does not get to
   average its way in.
4. It is admitted only if that worst speedup clears `1 + margin`. The margin
   exists so that run-to-run noise cannot promote a tie.

Anything unadmitted falls through to the baseline. A geometry with no winner is
a normal outcome, not a failure -- it is the fallback doing its job.
"""

from __future__ import annotations

import json
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Optional, Sequence

from . import harness, registry
from .paths import DISPATCH_TABLE, ensure_runs_dir
from .record import git_sha
from .shapes import Case

DEFAULT_MARGIN = 0.05

# Candidates that must never win a dispatch slot.
EXCLUDED = frozenset({"passthrough", "dispatch"})


@dataclass
class GroupDecision:
    dispatch_key: str
    cases: tuple[str, ...]
    winner: Optional[str]
    worst_speedup: Optional[float]
    margin: float
    rejected: dict[str, str]

    def to_entry(self, gpu: str, sha: str) -> dict[str, Any]:
        return {
            "candidate": self.winner,
            "worst_speedup": self.worst_speedup,
            "cases": list(self.cases),
            "margin": self.margin,
            "measured_on": gpu,
            "git_sha": sha,
            "rejected": self.rejected,
        }


def calibrate(
    cases: Iterable[Case],
    candidates: Optional[Sequence[str]] = None,
    *,
    margin: float = DEFAULT_MARGIN,
    results: Optional[Sequence[harness.EvalResult]] = None,
    **eval_kwargs: Any,
) -> tuple[list[GroupDecision], list[harness.EvalResult]]:
    cases = list(cases)
    names = [
        c.name
        for c in registry.resolve(candidates)
        if c.name not in EXCLUDED
    ]
    if results is None:
        results = harness.sweep(cases, names, **eval_kwargs)

    by_group: dict[str, dict[str, list[harness.EvalResult]]] = defaultdict(
        lambda: defaultdict(list)
    )
    for result in results:
        if result.candidate in EXCLUDED:
            continue
        by_group[result.case.dispatch_key][result.candidate].append(result)

    group_cases: dict[str, list[str]] = defaultdict(list)
    for case in cases:
        group_cases[case.dispatch_key].append(case.name)

    decisions = []
    for key in sorted(by_group):
        expected = set(group_cases.get(key, []))
        winner: Optional[str] = None
        best: Optional[float] = None
        rejected: dict[str, str] = {}

        for name, runs in sorted(by_group[key].items()):
            covered = {r.case.name for r in runs if r.ran}
            if expected - covered:
                rejected[name] = f"did not run on {sorted(expected - covered)}"
                continue
            failures = [r.case.name for r in runs if not r.passed]
            if failures:
                rejected[name] = f"failed correctness on {sorted(failures)}"
                continue
            worst = min(r.speedup for r in runs)
            if worst < 1.0 + margin:
                rejected[name] = f"worst speedup {worst:.3f}x below 1+{margin:g}"
                continue
            if best is None or worst > best:
                winner, best = name, worst

        decisions.append(
            GroupDecision(
                dispatch_key=key,
                cases=tuple(sorted(expected)),
                winner=winner,
                worst_speedup=best,
                margin=margin,
                rejected=rejected,
            )
        )
    return decisions, list(results)


def write_table(
    decisions: Sequence[GroupDecision],
    results: Sequence[harness.EvalResult],
    path: Optional[Path] = None,
) -> Path:
    path = Path(path or DISPATCH_TABLE)
    ensure_runs_dir()
    path.parent.mkdir(parents=True, exist_ok=True)

    gpu = next((r.gpu_name for r in results if r.ran), "unknown")
    device = next((r.device for r in results if r.ran), "unknown")
    sha = git_sha()

    payload = {
        "note": (
            "Generated by `odyssey calibrate`. A geometry appears here only if one "
            "candidate passed every case in its group and beat the baseline on the "
            "worst of them. Absent geometries fall back to the baseline path."
        ),
        "device": device,
        "gpu": gpu,
        "git_sha": sha,
        "entries": {
            d.dispatch_key: d.to_entry(gpu, sha)
            for d in decisions
            if d.winner is not None
        },
        "no_winner": {
            d.dispatch_key: d.rejected for d in decisions if d.winner is None
        },
    }
    path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")
    return path


def to_markdown(decisions: Sequence[GroupDecision]) -> str:
    lines = [
        "| Geometry | Serving | Worst-case speedup | Why not the others |",
        "|---|---|---:|---|",
    ]
    for d in decisions:
        winner = f"`{d.winner}`" if d.winner else "_baseline fallback_"
        speed = f"{d.worst_speedup:.3f}x" if d.worst_speedup else "--"
        why = "; ".join(f"`{k}`: {v}" for k, v in d.rejected.items()) or "--"
        lines.append(f"| `{d.dispatch_key}` | {winner} | {speed} | {why} |")
    return "\n".join(lines)
